
<script type="text/javascript" src="<?php echo base_url('jscr/qr_read/grid.js'); ?>"></script>
<script type="text/javascript" src="<?php echo base_url('jscr/qr_read/version.js'); ?>"></script>
<script type="text/javascript" src="<?php echo base_url('jscr/qr_read/detector.js'); ?>"></script>
<script type="text/javascript" src="<?php echo base_url('jscr/qr_read/formatinf.js'); ?>"></script>
<script type="text/javascript" src="<?php echo base_url('jscr/qr_read/errorlevel.js'); ?>"></script>
<script type="text/javascript" src="<?php echo base_url('jscr/qr_read/bitmat.js'); ?>"></script>
<script type="text/javascript" src="<?php echo base_url('jscr/qr_read/datablock.js'); ?>"></script>
<script type="text/javascript" src="<?php echo base_url('jscr/qr_read/bmparser.js'); ?>"></script>
<script type="text/javascript" src="<?php echo base_url('jscr/qr_read/datamask.js'); ?>"></script>
<script type="text/javascript" src="<?php echo base_url('jscr/qr_read/rsdecoder.js'); ?>"></script>
<script type="text/javascript" src="<?php echo base_url('jscr/qr_read/gf256poly.js'); ?>"></script>
<script type="text/javascript" src="<?php echo base_url('jscr/qr_read/gf256.js'); ?>"></script>
<script type="text/javascript" src="<?php echo base_url('jscr/qr_read/decoder.js'); ?>"></script>
<script type="text/javascript" src="<?php echo base_url('jscr/qr_read/qrcode.js'); ?>"></script>
<script type="text/javascript" src="<?php echo base_url('jscr/qr_read/findpat.js'); ?>"></script>
<script type="text/javascript" src="<?php echo base_url('jscr/qr_read/alignpat.js'); ?>"></script>
<script type="text/javascript" src="<?php echo base_url('jscr/qr_read/databr.js'); ?>"></script>
<script type="text/javascript" src="<?php echo base_url('jscr/jquery_min.js'); ?>"></script>
